//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmGard.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201605030454123_AddBlogVersion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201605030454123_AddBlogVersion() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GmGard.Migrations.201605030454123_AddBlogVersion", typeof(_201605030454123_AddBlogVersion).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1dW2/cOpJ+X2D/Q6OfZnbOuG0nOZMJ7Bk4TnKOMbnBl+y+GUo30xailnoktY+Nxf6yfdiftH9hSVEUb0WKlCi1nD3wi5sUi8Wqj8VbFfm///0/J39/2CSze5QXcZaezo8ODuczlC6zVZyuT+e78tufX87//rd//ZeTt6vNw+wL++4Z+Q6XTIvT+V1Zbl8tFsXyDm2i4mATL/OsyL6VB8tss4hW2eL48PCvi6OjBcIk5pjWbHZyuUvLeIOqH/jneZYu0bbcRcmHbIWSok7HOVcV1dnHaIOKbbREp/MPjx++nP87+npAP53PzpI4wmxcoeTbfBalaVZGJWby1U2Brso8S9dXW5wQJdePW4S/+xYlBaqZf8U/d23H4TFpx4IXZKSWu6LMNp4Ej57VglmoxTuJd94IrhLqZpugB9LsSn6n88so/Y5Wr5NsfbGaz9QaX50nOflYE/GBWO6nGcv9qYEDRg35+2l2vkvKXY5OU7Qr8yj5afZ5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
