//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmGard.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201603170316438_InitialCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201603170316438_InitialCreate() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GmGard.Migrations.201603170316438_InitialCreate", typeof(_201603170316438_InitialCreate).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1d3W7cOJa+X2DfoVBXM4uMy3aSnkxgz8BxOt3GxEngn+zeBUoVUxaikmokldvGYp9sL/aR5hWGFEXx75AiJUoqZxu+cZHiIXnOx8O/j+Q///f/Tv72sElm9ygv4iw9nR8dHM5nKF1mqzhdn8535bc/vZr/7a///m8nP682D7PP7Lvn5DucMi1O53dluX29WBTLO7SJioNNvMyzIvtWHiyzzSJaZYvjw8O/LI6OFgiLmGNZs9nJ1S4t4w2qfuCf51m6RNtyFyWX2QolRR2OY64rqbMP0QYV22iJTueXj5efz/8TfT2gn85nZ0kc4WJco+TbfBalaVZGJS7k69sCXZd5lq6vtzggSm4etwh/9y1KClQX/jX/3LUeh8ekHguekIla7ooy23gKPHpeK2ahJu+k3nmjuEqpm22CHki1K/2dzq+i9DtavUmy9cVqPlNzfH2e5ORjTcUHYrpnMxb7rIEDRg35ezY73yXlLkenKdqVeZQ8m33a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
