//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmGard.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201603170322056_AddAudit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201603170322056_AddAudit() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GmGard.Migrations.201603170322056_AddAudit", typeof(_201603170322056_AddAudit).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1d23LcOJJ934j9h4p6mtnpUUmy3eNxSDMhy+1uxciX0KV33xR0FVximEXWkCy1FBv7Zfuwn7S/sABBELcECJAgi/J26EUFEIlE5kHilgn873//z8nfHzfJ7AHlRZylp/Ojg8P5DKXLbBWn69P5rvz659fzv//tX//l5KfV5nH2K/vuBfkOl0yL0/l9WW7fLBbF8h5touJgEy/zrMi+lgfLbLOIVtni+PDwr4ujowXCJOaY1mx2crVLy3iDqh/453mWLtG23EXJh2yFkqJOxznXFdXZx2iDim20RKfzD08ffj3/d/TlgH46n50lcYTZuEbJ1/ksStOsjErM5JvbAl2XeZaur7c4IUpunrYIf/c1SgpUM/+Gf+7ajsNj0o4FL8hILXdFmW08CR69qAWzUIt3Eu+8EVwl1M02QY+k2ZX8TudXUfoNrd4m2fpiNZ+pNb45T3LysSbiA7HcDzOW+0MDB4wa8vfD7HyXlLscnaZoV+ZR8sPs [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
