// <auto-generated />
namespace MyMVCWeb.UserMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddGameChoices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGameChoices));
        
        string IMigrationMetadata.Id
        {
            get { return "201610220232223_AddGameChoices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
