// <auto-generated />
namespace MyMVCWeb.UserMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addCreateDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCreateDate));

        string IMigrationMetadata.Id
        {
            get { return "201607250436405_addCreateDate"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
