// <auto-generated />
namespace MyMVCWeb.UserMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPunchinMakeup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPunchinMakeup));
        
        string IMigrationMetadata.Id
        {
            get { return "201903110905118_AddPunchinMakeup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
