// <auto-generated />
namespace MyMVCWeb.UserMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddShowDateOnListOption : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddShowDateOnListOption));
        
        string IMigrationMetadata.Id
        {
            get { return "202108301048297_AddShowDateOnListOption"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
