// <auto-generated />
namespace MyMVCWeb.UserMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddChoiceData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChoiceData));
        
        string IMigrationMetadata.Id
        {
            get { return "202308100851171_AddChoiceData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
