// <auto-generated />
using System;
using GmGard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GmGard.Migrations.Users
{
    [DbContext(typeof(UsersContext))]
    [Migration("20251124134047_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmGard.Models.AdminLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Actor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Target")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LogID");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("GmGard.Models.AuditExamSubmission", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnOrder(2);

                    b.Property<bool>("HasPassed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("boolean");

                    b.Property<string>("RawResult")
                        .HasColumnType("text");

                    b.Property<string>("RawSubmission")
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserID", "Version");

                    b.ToTable("AuditExamSubmissions");
                });

            modelBuilder.Entity("GmGard.Models.Auditor", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("AuditCount")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.HasKey("UserID");

                    b.ToTable("Auditors");
                });

            modelBuilder.Entity("GmGard.Models.ExperienceTable", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceEnd")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceStart")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Level");

                    b.ToTable("ExpTable");
                });

            modelBuilder.Entity("GmGard.Models.Follow", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("FollowID")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("FollowTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserID", "FollowID");

                    b.HasIndex("FollowID");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("GmGard.Models.GachaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasMission")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GachaItems");
                });

            modelBuilder.Entity("GmGard.Models.GachaPool", b =>
                {
                    b.Property<int>("Name")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Name", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("GachaPools");
                });

            modelBuilder.Entity("GmGard.Models.GachaTitleConditionConfig", b =>
                {
                    b.Property<int>("ConditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConditionID"));

                    b.Property<string>("ConditionRequirements")
                        .HasColumnType("text");

                    b.Property<string>("ConditionType")
                        .HasColumnType("text");

                    b.Property<int>("TitleID")
                        .HasColumnType("integer");

                    b.HasKey("ConditionID");

                    b.HasIndex("TitleID");

                    b.ToTable("GachaTitleConditionConfigs");
                });

            modelBuilder.Entity("GmGard.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameID"));

                    b.Property<string>("GameChapters")
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<string>("ItemList")
                        .HasColumnType("text");

                    b.HasKey("GameID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GmGard.Models.GameScenario", b =>
                {
                    b.Property<int>("ScenarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScenarioID"));

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Dialogs")
                        .HasColumnType("text");

                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<string>("Narrators")
                        .HasColumnType("text");

                    b.HasKey("ScenarioID");

                    b.HasIndex("GameID");

                    b.ToTable("GameScenarios");
                });

            modelBuilder.Entity("GmGard.Models.Message", b =>
                {
                    b.Property<int>("MsgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MsgId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecipientDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSenderDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("MsgContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MsgDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MsgTitle")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MsgId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GmGard.Models.Pictures", b =>
                {
                    b.Property<int>("PicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PicID"));

                    b.Property<DateTime>("PicDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PicName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PicType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PicUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PicID");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("GmGard.Models.PunchInHistory", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsMakeup")
                        .HasColumnType("boolean");

                    b.HasKey("UserID", "TimeStamp");

                    b.ToTable("PunchInHistories");
                });

            modelBuilder.Entity("GmGard.Models.RaffleConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int>("RaffleCost")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RaffleConfigs");
                });

            modelBuilder.Entity("GmGard.Models.ScenarioChoice", b =>
                {
                    b.Property<int>("ScenarioID")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("NextScenarioID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("ChoiceData")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ScenarioID", "NextScenarioID");

                    b.HasIndex("NextScenarioID");

                    b.ToTable("ScenarioChoices");
                });

            modelBuilder.Entity("GmGard.Models.TitleConfig", b =>
                {
                    b.Property<int>("TitleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TitleID"));

                    b.Property<string>("TitleDescription")
                        .HasColumnType("text");

                    b.Property<string>("TitleImage")
                        .HasColumnType("text");

                    b.Property<string>("TitleName")
                        .HasColumnType("text");

                    b.HasKey("TitleID");

                    b.ToTable("TitleConfigs");
                });

            modelBuilder.Entity("GmGard.Models.TreasureHuntAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttemptId"));

                    b.Property<string>("AttemptAnswer")
                        .HasColumnType("text");

                    b.Property<DateTime>("AttemptTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("TargetPuzzle")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("AttemptId");

                    b.HasIndex("UserID");

                    b.ToTable("TreasureHuntAttempts");
                });

            modelBuilder.Entity("GmGard.Models.UserCode", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BuyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UsedBy")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("UsedBy");

                    b.HasIndex("UserId");

                    b.ToTable("UserCodes");
                });

            modelBuilder.Entity("GmGard.Models.UserGacha", b =>
                {
                    b.Property<int>("GachaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GachaId"));

                    b.Property<DateTime>("GachaTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PoolName")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("GachaId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserID");

                    b.ToTable("UserGachas");
                });

            modelBuilder.Entity("GmGard.Models.UserGameData", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("GameID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("CurrentScenarioID")
                        .HasColumnType("integer");

                    b.Property<string>("Inventory")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("UserID", "GameID");

                    b.HasIndex("CurrentScenarioID");

                    b.HasIndex("GameID");

                    b.ToTable("UserGameDatas");
                });

            modelBuilder.Entity("GmGard.Models.UserOption", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowBlogDateOnLists")
                        .HasColumnType("boolean");

                    b.Property<bool>("addFavFlameEffect")
                        .HasColumnType("boolean");

                    b.Property<string>("homepageCategories")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("homepageHideHarmony")
                        .HasColumnType("boolean");

                    b.Property<string>("homepageTagBlacklist")
                        .HasColumnType("text");

                    b.Property<bool>("sendNoticeForNewPostReply")
                        .HasColumnType("boolean");

                    b.Property<bool>("sendNoticeForNewReply")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("UserOptions");
                });

            modelBuilder.Entity("GmGard.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveSign")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("HistoryConsecutiveSign")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastLoginIP")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("LastSignDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserComment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UserEmailIndex");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("NormalizedEmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("NormalizedUserNameIndex");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.UserQuest", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DayBlogCount")
                        .HasColumnType("integer");

                    b.Property<int>("DeathCount")
                        .HasColumnType("integer");

                    b.Property<int>("EternalCircleProgress")
                        .HasColumnType("integer");

                    b.Property<int>("EternalCircleRetryCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("GameChoices")
                        .HasColumnType("bytea");

                    b.Property<bool>("HasGotReward")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastBlogDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastPostDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastRateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastRatePostDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PersonalBackground")
                        .HasColumnType("text");

                    b.Property<int>("Profession")
                        .HasColumnType("integer");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<int>("PunchInTicket")
                        .HasColumnType("integer");

                    b.Property<int>("Title")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Titles")
                        .HasColumnType("bytea");

                    b.Property<int>("WeekBlogCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Title");

                    b.ToTable("UserQuests");
                });

            modelBuilder.Entity("GmGard.Models.UserRaffle", b =>
                {
                    b.Property<Guid>("RaffleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConfigId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("RaffleID");

                    b.HasIndex("ConfigId");

                    b.HasIndex("UserID");

                    b.ToTable("UserRaffles");
                });

            modelBuilder.Entity("GmGard.Models.UserVisitedScenario", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("GameID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("ScenarioID")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserID", "GameID", "ScenarioID", "Attempt");

                    b.HasIndex("ScenarioID");

                    b.ToTable("UserVisitedScenarios");
                });

            modelBuilder.Entity("GmGard.Models.UserVoucher", b =>
                {
                    b.Property<Guid>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IssueTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RedeemItem")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UseTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("VoucherKind")
                        .HasColumnType("integer");

                    b.HasKey("VoucherID");

                    b.HasIndex("UserID");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNormalizedNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey", "UserId")
                        .HasName("PK_AspNetUserLogins");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_AspNetUserRoles");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("PK_AspNetUserTokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.AuditExamSubmission", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GmGard.Models.Auditor", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", "User")
                        .WithOne("auditor")
                        .HasForeignKey("GmGard.Models.Auditor", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GmGard.Models.Follow", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", "follow")
                        .WithMany()
                        .HasForeignKey("FollowID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GmGard.Models.UserProfile", "user")
                        .WithMany("follows")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("follow");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GmGard.Models.GachaPool", b =>
                {
                    b.HasOne("GmGard.Models.GachaItem", "Item")
                        .WithMany("Pools")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GmGard.Models.GachaTitleConditionConfig", b =>
                {
                    b.HasOne("GmGard.Models.TitleConfig", "TitleConfig")
                        .WithMany()
                        .HasForeignKey("TitleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TitleConfig");
                });

            modelBuilder.Entity("GmGard.Models.GameScenario", b =>
                {
                    b.HasOne("GmGard.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GmGard.Models.PunchInHistory", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", "User")
                        .WithMany("PunchIns")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GmGard.Models.ScenarioChoice", b =>
                {
                    b.HasOne("GmGard.Models.GameScenario", "NextScenario")
                        .WithMany()
                        .HasForeignKey("NextScenarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.GameScenario", "Scenario")
                        .WithMany("Choices")
                        .HasForeignKey("ScenarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NextScenario");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("GmGard.Models.TreasureHuntAttempt", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GmGard.Models.UserCode", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedBy");

                    b.HasOne("GmGard.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GmGard.Models.UserGacha", b =>
                {
                    b.HasOne("GmGard.Models.GachaItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GmGard.Models.UserGameData", b =>
                {
                    b.HasOne("GmGard.Models.GameScenario", "CurrentScenario")
                        .WithMany()
                        .HasForeignKey("CurrentScenarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GmGard.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentScenario");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GmGard.Models.UserOption", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", "user")
                        .WithOne("option")
                        .HasForeignKey("GmGard.Models.UserOption", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("GmGard.Models.UserQuest", b =>
                {
                    b.HasOne("GmGard.Models.TitleConfig", "TitleConfig")
                        .WithMany()
                        .HasForeignKey("Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.UserProfile", "user")
                        .WithOne("quest")
                        .HasForeignKey("GmGard.Models.UserQuest", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TitleConfig");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GmGard.Models.UserRaffle", b =>
                {
                    b.HasOne("GmGard.Models.RaffleConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId");

                    b.HasOne("GmGard.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GmGard.Models.UserVisitedScenario", b =>
                {
                    b.HasOne("GmGard.Models.GameScenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.UserGameData", "UserGameData")
                        .WithMany("VisitedScenarios")
                        .HasForeignKey("UserID", "GameID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("UserGameData");
                });

            modelBuilder.Entity("GmGard.Models.UserVoucher", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GmGard.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GmGard.Models.GachaItem", b =>
                {
                    b.Navigation("Pools");
                });

            modelBuilder.Entity("GmGard.Models.GameScenario", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("GmGard.Models.UserGameData", b =>
                {
                    b.Navigation("VisitedScenarios");
                });

            modelBuilder.Entity("GmGard.Models.UserProfile", b =>
                {
                    b.Navigation("PunchIns");

                    b.Navigation("auditor");

                    b.Navigation("follows");

                    b.Navigation("option");

                    b.Navigation("quest");
                });
#pragma warning restore 612, 618
        }
    }
}
