// <auto-generated />
using System;
using GmGard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GmGard.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmGard.Models.Advertisment", b =>
                {
                    b.Property<int>("AdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdID"));

                    b.Property<int?>("AdOrder")
                        .HasColumnType("integer");

                    b.Property<string>("AdTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AdType")
                        .HasColumnType("integer");

                    b.Property<string>("AdUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<string>("ImgUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("AdID");

                    b.ToTable("Advertisments", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<int>("BountyId")
                        .HasColumnType("integer");

                    b.Property<int?>("BountyId1")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.HasKey("AnswerId");

                    b.HasIndex("BountyId");

                    b.HasIndex("BountyId1")
                        .IsUnique();

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Blog", b =>
                {
                    b.Property<int>("BlogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BlogID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("BlogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlogTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("BlogVisit")
                        .HasColumnType("bigint");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsLocalImg")
                        .HasColumnType("boolean");

                    b.Property<string>("Links")
                        .HasColumnType("text");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<bool?>("isApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("isHarmony")
                        .HasColumnType("boolean");

                    b.HasKey("BlogID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Blogs", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.BlogAudit", b =>
                {
                    b.Property<int>("BlogID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("Auditor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnOrder(2);

                    b.Property<int>("BlogVersion")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<int>("AuditAction")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("BlogID", "Auditor", "BlogVersion");

                    b.ToTable("BlogAudits", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.BlogOption", b =>
                {
                    b.Property<int>("BlogID")
                        .HasColumnType("integer");

                    b.Property<string>("LockDesc")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("LockTags")
                        .HasColumnType("boolean");

                    b.Property<bool>("NoApprove")
                        .HasColumnType("boolean");

                    b.Property<bool>("NoComment")
                        .HasColumnType("boolean");

                    b.Property<bool>("NoRate")
                        .HasColumnType("boolean");

                    b.HasKey("BlogID");

                    b.ToTable("BlogOptions", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.BlogRating", b =>
                {
                    b.Property<Guid>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlogID")
                        .HasColumnType("integer");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("credential")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ratetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("value")
                        .HasColumnType("integer");

                    b.HasKey("RatingID");

                    b.HasIndex("BlogID");

                    b.HasIndex("PostId");

                    b.ToTable("Ratings", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.BlogsInTopic", b =>
                {
                    b.Property<int>("TopicID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("BlogID")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("BlogOrder")
                        .HasColumnType("integer");

                    b.HasKey("TopicID", "BlogID");

                    b.HasIndex("BlogID");

                    b.ToTable("BlogsInTopics", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Bounty", b =>
                {
                    b.Property<int>("BountyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BountyId"));

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("text");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Prize")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("BountyId");

                    b.ToTable("Bounties", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("DisableRanking")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisableRating")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideFromHomePage")
                        .HasColumnType("boolean");

                    b.Property<bool>("LinkOptional")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("integer");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Favorite", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnOrder(1);

                    b.Property<int>("BlogID")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Username", "BlogID");

                    b.HasIndex("BlogID");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.HanGroup", b =>
                {
                    b.Property<int>("HanGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HanGroupID"));

                    b.Property<string>("GroupUri")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Intro")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Logo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("HanGroupID");

                    b.ToTable("HanGroups", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.HanGroupBlog", b =>
                {
                    b.Property<int>("HanGroupID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("BlogID")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.HasKey("HanGroupID", "BlogID");

                    b.HasIndex("BlogID");

                    b.ToTable("HanGroupBlogs", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.HanGroupMember", b =>
                {
                    b.Property<int>("HanGroupID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnOrder(2);

                    b.Property<int>("GroupLvl")
                        .HasColumnType("integer");

                    b.HasKey("HanGroupID", "Username");

                    b.ToTable("HanGroupMembers", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.HistoryRanking", b =>
                {
                    b.Property<DateTime>("RankDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<int>("BlogID")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("RankType")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlogThumb")
                        .HasColumnType("text");

                    b.Property<string>("BlogTitle")
                        .HasColumnType("text");

                    b.Property<long>("BlogVisit")
                        .HasColumnType("bigint");

                    b.Property<int>("PostCount")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("RankDate", "BlogID", "RankType");

                    b.ToTable("HistoryRankings", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<string>("Author")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<int>("IdType")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("PostId");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.PostRating", b =>
                {
                    b.Property<Guid>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("Rater")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("RatingID");

                    b.HasIndex("PostId");

                    b.ToTable("PostRatings", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Reply", b =>
                {
                    b.Property<int>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplyId"));

                    b.Property<string>("Author")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReplyDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReplyId");

                    b.HasIndex("PostId");

                    b.ToTable("Replies", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagID"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("TagVisit")
                        .HasColumnType("bigint");

                    b.HasKey("TagID");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.TagHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryID"));

                    b.Property<string>("AddBy")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("BlogID")
                        .HasColumnType("integer");

                    b.Property<string>("DeleteBy")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TagName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HistoryID");

                    b.HasIndex("BlogID");

                    b.ToTable("TagHistories", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.TagsInBlog", b =>
                {
                    b.Property<int>("BlogID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("TagID")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<string>("AddBy")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("BlogID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("TagsInBlogs", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Topic", b =>
                {
                    b.Property<int>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopicID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BannerPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TagID")
                        .HasColumnType("integer");

                    b.Property<string>("TopicTitle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long>("TopicVisit")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isLocalImg")
                        .HasColumnType("boolean");

                    b.HasKey("TopicID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("TagID");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("GmGard.Models.Answer", b =>
                {
                    b.HasOne("GmGard.Models.Bounty", "Bounty")
                        .WithMany("Answers")
                        .HasForeignKey("BountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.Bounty", null)
                        .WithOne("AcceptedAnswer")
                        .HasForeignKey("GmGard.Models.Answer", "BountyId1");

                    b.Navigation("Bounty");
                });

            modelBuilder.Entity("GmGard.Models.Blog", b =>
                {
                    b.HasOne("GmGard.Models.Category", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GmGard.Models.BlogAudit", b =>
                {
                    b.HasOne("GmGard.Models.Blog", "blog")
                        .WithMany("blogAudits")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog");
                });

            modelBuilder.Entity("GmGard.Models.BlogOption", b =>
                {
                    b.HasOne("GmGard.Models.Blog", "blog")
                        .WithOne("option")
                        .HasForeignKey("GmGard.Models.BlogOption", "BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog");
                });

            modelBuilder.Entity("GmGard.Models.BlogRating", b =>
                {
                    b.HasOne("GmGard.Models.Blog", "blog")
                        .WithMany()
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.Post", "post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.Navigation("blog");

                    b.Navigation("post");
                });

            modelBuilder.Entity("GmGard.Models.BlogsInTopic", b =>
                {
                    b.HasOne("GmGard.Models.Blog", "blog")
                        .WithMany()
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.Topic", "topic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog");

                    b.Navigation("topic");
                });

            modelBuilder.Entity("GmGard.Models.Category", b =>
                {
                    b.HasOne("GmGard.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryID");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("GmGard.Models.Favorite", b =>
                {
                    b.HasOne("GmGard.Models.Blog", "blog")
                        .WithMany()
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog");
                });

            modelBuilder.Entity("GmGard.Models.HanGroupBlog", b =>
                {
                    b.HasOne("GmGard.Models.Blog", "blog")
                        .WithMany()
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.HanGroup", "hangroup")
                        .WithMany("blogs")
                        .HasForeignKey("HanGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog");

                    b.Navigation("hangroup");
                });

            modelBuilder.Entity("GmGard.Models.HanGroupMember", b =>
                {
                    b.HasOne("GmGard.Models.HanGroup", "hangroup")
                        .WithMany("members")
                        .HasForeignKey("HanGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hangroup");
                });

            modelBuilder.Entity("GmGard.Models.PostRating", b =>
                {
                    b.HasOne("GmGard.Models.Post", "Post")
                        .WithMany("Ratings")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("GmGard.Models.Reply", b =>
                {
                    b.HasOne("GmGard.Models.Post", "post")
                        .WithMany("Replies")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("post");
                });

            modelBuilder.Entity("GmGard.Models.TagHistory", b =>
                {
                    b.HasOne("GmGard.Models.Blog", "blog")
                        .WithMany()
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog");
                });

            modelBuilder.Entity("GmGard.Models.TagsInBlog", b =>
                {
                    b.HasOne("GmGard.Models.Blog", "blog")
                        .WithMany()
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.Tag", "tag")
                        .WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("GmGard.Models.Topic", b =>
                {
                    b.HasOne("GmGard.Models.Category", null)
                        .WithMany("Topics")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmGard.Models.Tag", "tag")
                        .WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tag");
                });

            modelBuilder.Entity("GmGard.Models.Blog", b =>
                {
                    b.Navigation("blogAudits");

                    b.Navigation("option");
                });

            modelBuilder.Entity("GmGard.Models.Bounty", b =>
                {
                    b.Navigation("AcceptedAnswer");

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("GmGard.Models.Category", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("SubCategories");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("GmGard.Models.HanGroup", b =>
                {
                    b.Navigation("blogs");

                    b.Navigation("members");
                });

            modelBuilder.Entity("GmGard.Models.Post", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
